### ISSUE TITLE
Step 1 - Run the benchmark failed

### ISSUE THREAD

**Issue by MaherJendoubi** [ajcvickers/CompiledModelsDemo#1]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.

**Comment by ajcvickers** [comment]
You'll need to update the connection string.

**Comment by MaherJendoubi** [comment]
@ajcvickers My bad, I miss that one. I have just fixed it. Thank you.



// * **Before** *

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19043.1023 (21H1/May2021Update)
**Intel Xeon Platinum 8171M CPU 2.60GHz, 1 CPU, 16 logical and 8 physical cores**
.NET SDK=6.0.100-preview.4.21255.9
  [Host]     : .NET 5.0.5 (5.0.521.16609), X64 RyuJIT  [AttachedDebugger]
  Job-ZDDCNE : .NET 5.0.5 (5.0.521.16609), X64 RyuJIT

InvocationCount=1  IterationCount=20  UnrollFactor=1

|           Method |    Mean |    Error |   StdDev |
|----------------- |--------:|---------:|---------:|
| TimeToFirstQuery | **2.190 s** | 0.0377 s | 0.0419 s |


// * **After** *

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19043.1023 (21H1/May2021Update)
**Intel Xeon Platinum 8171M CPU 2.60GHz, 1 CPU, 16 logical and 8 physical cores**
.NET SDK=6.0.100-preview.4.21255.9
  [Host]     : .NET 5.0.5 (5.0.521.16609), X64 RyuJIT  [AttachedDebugger]
  Job-WVFRJB : .NET 5.0.5 (5.0.521.16609), X64 RyuJIT

InvocationCount=1  IterationCount=20  UnrollFactor=1

|           Method |     Mean |   Error |  StdDev |
|----------------- |---------:|--------:|--------:|
| TimeToFirstQuery | **179.6 ms** | 5.79 ms | 6.66 ms |
